name = "personal-assistant-agent"
account_id = "28a29a934ac59a2e7887972b9cb042e2"
main = "src/index.js"
workers_dev = false
compatibility_date = "2025-05-25"

[[kv_namespaces]]
binding = "USERS_KV"
id = "09653d527f3a46688c1ed5cf2bca446c"


[vars]
ENVIRONMENT = "production"

[triggers]
crons = []

# Custom domain configuration
[[routes]]
pattern = "aivelle.com/*"
zone_id = "25bfeae0a291ab9d467fec3117a64c85"
