// src/workflow-engine.js

import logger from "./utils/logger.js";
import * as voiceToAnywhere from "./workflows/automation/voice_to_anywhere.js";
import * as attachImageToAnyPost from "./workflows/automation/attach_image_to_any_post.js";
import * as contentRepurpose from "./workflows/automation/content_repurpose.js";
import * as rescheduleMeeting from "./workflows/automation/reschedule_meeting.js";
import * as dailyIntentDigest from "./workflows/automation/daily_intent_digest.js";
import * as autoTagging from "./workflows/automation/auto_tagging.js";
import * as autoReply from "./workflows/automation/auto_reply.js";
// NOTE: These imports can be auto-generated by a build script in the future.

const workflows = {
  voice_to_anywhere: voiceToAnywhere,
  attach_image_to_any_post: attachImageToAnyPost,
  content_repurpose: contentRepurpose,
  reschedule_meeting: rescheduleMeeting,
  daily_intent_digest: dailyIntentDigest,
  auto_tagging: autoTagging,
  auto_reply: autoReply,
};

/**
 * Runs the workflow for the given intent
 * @param {string} intent - The intent name
 * @param {string} prompt - The original user prompt
 * @param {object} [context={}] - Optional context
 * @returns {Promise<object>} - Result of the workflow
 */
export async function runWorkflow(intent, prompt, context = {}) {
  const workflow = workflows[intent];
  if (!workflow || !workflow.run) {
    logger.error(`No workflow found for intent: ${intent}`);
    return {
      success: false,
      message: `❌ No workflow found for intent: ${intent}`,
    };
  }

  try {
    logger.info(`Running workflow for intent: ${intent}`);
    const result = await workflow.run({ prompt, context });
    return {
      success: true,
      intent,
      prompt,
      result,
    };
  } catch (err) {
    logger.error(`Error running workflow for intent ${intent}:`, err);
    return {
      success: false,
      message: `❌ Error running workflow: ${err.message}`,
    };
  }
}

export { workflows }; 